### ISSUE TITLE
User is null on HomeViewModel

### ISSUE THREAD

**Issue by nirazv** [mohit-sharma-87/RChatApp#1]
User model class defined inside data.Models.kt was firstly called on HomeViewModel using following method/query
on Line no 55

` val result = realm.where<User>().equalTo("_id", user.id).findAll()`

but it was always null as you have not inserted or executed any transaction for insertion?

I have also checked the login part but not found any insertion query

The whole code look likes

` Realm.getInstanceAsync(config, object : Realm.Callback() {
            override fun onSuccess(realm: Realm) {
                val result = realm.where<User>().equalTo("_id", user.id).findAll()
                result.addChangeListener(RealmChangeListener<RealmResults<User>> {
                    it.first()?.let { //it will be always null
                        realm.copyFromRealm(it).apply {
                            _chatList.value = this?.conversations ?: emptyList()
                        }
                    }
                })
}`

I am also curious to know what exactly copyFromRealm() does here?

**Comment by mohit-sharma-87** [comment]
@nirazv :  User is not null in HomeViewModel.

User is inserted in the document using a [trigger on User Registration.](https://www.mongodb.com/developer/how-to/building-a-mobile-chat-app-using-realm-new-way/#create-)

Also, copyFromRealm is used to create a copy of data from Realm, for more information refer to our [documentation](https://www.mongodb.com/docs/realm/sdk/java/api/io/realm/Realm/#std-label-io_realm_Realm_copyFromRealm).

**Comment by nirazv** [comment]
In trigger function you're particularly specifying the name of the database to insert
Ex - `const db = context.services.get("mongodb-atlas").db("RChat");`
but in android app how can we specify the database name?
