### ISSUE TITLE
How to change/select database in realm

### ISSUE THREAD

**Issue by nirazv** [mohit-sharma-87/RChatApp#2]
By default when we initialize our app with realmSync,it uses the default database with our android/ios app name. But in the cloud we might have several databases and for some reason if someone wants to change the database how would he do that in android?

Currently we use Realm.init() to initialize for android 

`Realm.init(context)`

**Comment by mohit-sharma-87** [comment]
@nirazv: Can you move this question to [MongoDB forum](https://www.mongodb.com/community/forums/), as it's more of a knowledge-based question rather than an issue with the codebase.
